global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'catalog-service'
    static_configs:
      - targets: ['host.docker.internal:4000']
  - job_name: 'order-service'
    static_configs:
      - targets: ['host.docker.internal:4001']